# Generated by Django 3.1.2 on 2020-10-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinme_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='num_people',
            field=models.IntegerField(default=0),
        ),
    ]
