# Generated by Django 3.1.2 on 2020-10-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinme_app', '0002_activity_num_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='province',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='zip',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
